import { Metadata } from "next";
import Layout from "@/components/layout";
import { Web3Modal } from "@/context/Web3Modal";

import "@/styles/globals.css";
import type { AppProps } from "next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Web3Modal>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Web3Modal>
  );
}
